name: calendar_dart
description: A Dart port of Python's calendar library.
version: 0.0.1
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
